# Reporting Events DB (MongoDB) secret for Finance Portal subcharts
apiVersion: v1
kind: Secret
metadata:
  name: reporting-events-db-secret
  namespace: mojaloop
type: Opaque
stringData:
  mongodb-password: "${mongodb_app_password}"
---
# Keycloak client secret for role-assignment-service
apiVersion: v1
kind: Secret
metadata:
  name: role-assign-svc-secret
  namespace: mojaloop
type: Opaque
stringData:
  secret: "${role_assign_svc_secret}"
