apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mojaloop/helmrelease.yaml
  - mcm/helmrelease.yaml
  - mcm/secrets.yaml
  - finance-portal/helmrelease.yaml
  - finance-portal/secrets.yaml
