apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ory-rbac-role-permissions.yaml
  - ory-blank-rule.yaml
  - mojaloop/helmrelease.yaml
  - mcm/helmrelease.yaml
  - mcm/secrets.yaml
  - mcm/oathkeeper-rules.yaml
  - mcm/referencegrant.yaml
  - finance-portal/helmrelease.yaml
  - finance-portal/externalsecret-role-assign-svc.yaml
  - finance-portal/externalsecret-reporting-events-db.yaml
  - finance-portal/oathkeeper-rules.yaml
  - finance-portal/referencegrant.yaml
