apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: bulk-mongodb
  namespace: mojaloop
spec:
  crVersion: "1.21.0"
  image: percona/percona-server-mongodb:7.0
  allowUnsafeConfigurations: true
  secrets:
    users: bulk-mongodb-secrets
  replsets:
    - name: rs0
      size: 3
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
  sharding:
    enabled: false
