apiVersion: v1
kind: Secret
metadata:
  name: bulk-mongodb-secrets
  namespace: mojaloop
type: Opaque
stringData:
  MONGODB_BACKUP_USER: backup
  MONGODB_BACKUP_PASSWORD: "${mongodb_root_password}"
  MONGODB_CLUSTER_ADMIN_USER: clusterAdmin
  MONGODB_CLUSTER_ADMIN_PASSWORD: "${mongodb_root_password}"
  MONGODB_CLUSTER_MONITOR_USER: clusterMonitor
  MONGODB_CLUSTER_MONITOR_PASSWORD: "${mongodb_root_password}"
  MONGODB_USER_ADMIN_USER: userAdmin
  MONGODB_USER_ADMIN_PASSWORD: "${mongodb_root_password}"
---
apiVersion: v1
kind: Secret
metadata:
  name: bulk-mongodb-app-secrets
  namespace: mojaloop
type: Opaque
stringData:
  MONGODB_APP_USER: mojaloop
  MONGODB_APP_PASSWORD: "${mongodb_app_password}"
