apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keto
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: keto
      version: "0.39.0"
      sourceRef:
        kind: HelmRepository
        name: ory
      interval: 12h
  targetNamespace: ory
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      strategy: uninstall
  values:
    fullnameOverride: "keto"

    secret:
      enabled: false
      nameOverride: keto-secret

    keto:
      automigration:
        enabled: true
        type: initContainer
      config:
        dsn: "mysql://keto:${keto_db_password}@tcp(${auth_db_host}.mojaloop.svc.cluster.local:3306)/keto?max_conns=20&max_idle_conns=4"
        serve:
          read:
            port: 4466
          write:
            port: 4467
          metrics:
            port: 4468
        namespaces:
          - id: 0
            name: role
          - id: 1
            name: permission
          - id: 2
            name: participant
