apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault/vault.yaml
  - vault/secretstore.yaml
  - minio/externalsecret.yaml
  - minio/helmrelease.yaml
  - harbor/externalsecret.yaml
  - harbor/helmrelease.yaml
  - gateway/gateway.yaml
  - gateway/routes.yaml
