apiVersion: v1
kind: Service
metadata:
  name: keycloak-metrics
  namespace: keycloak
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
