apiVersion: v1
kind: Secret
metadata:
  name: central-ledger-db-secrets
  namespace: mojaloop
type: Opaque
stringData:
  root: "${mysql_root_password}"
  xtrabackup: "${mysql_root_password}"
  monitor: "${mysql_root_password}"
  operator: "${mysql_root_password}"
  replication: "${mysql_root_password}"
---
apiVersion: v1
kind: Secret
metadata:
  name: account-lookup-db-secrets
  namespace: mojaloop
type: Opaque
stringData:
  root: "${mysql_root_password}"
  xtrabackup: "${mysql_root_password}"
  monitor: "${mysql_root_password}"
  operator: "${mysql_root_password}"
  replication: "${mysql_root_password}"
---
# Default secret name expected by Mojaloop Helm chart for DB password references
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb
  namespace: mojaloop
type: Opaque
stringData:
  mysql-password: "${mysql_central_ledger_password}"
  mysql-als-password: "${mysql_account_lookup_password}"
  mysql-oracle-password: "${mysql_oracle_msisdn_password}"
